# Generated by Django 4.2.4 on 2023-08-13 12:11

from django.db import migrations, models

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('store_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('timezone_str', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'store_time_zone',
            },
        )
    ]
