# Generated by Django 4.2.4 on 2023-08-13 12:39

from django.db import migrations
from django.conf import settings
import csv
import os

def store_business_hour_csv(apps, schema_editor):
    Store = apps.get_model('store_time_zone', 'Store')
    BusinessHours = apps.get_model('store_business_hours', 'BusinessHours')
    with open(os.path.join(settings.CSV_PATH, 'business_hours.csv')) as csvfile:
        reader = csv.DictReader(csvfile)
        for row in reader:
            store = Store.objects.filter(store_id=row['store_id']).first()
            if store:
                BusinessHours.objects.create(
                    store=store,
                    day=row['day'],
                    start_time=row['start_time_local'],
                    end_time=row['end_time_local'],
                )

class Migration(migrations.Migration):

    dependencies = [
        ('store_business_hours', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(store_business_hour_csv,reverse_code=migrations.RunPython.noop)
    ]
