# Generated by Django 4.2.4 on 2023-08-13 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store_time_zone', '0002_auto_20230813_1230'),
    ]

    operations = [
        migrations.CreateModel(
            name='PollingLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')])),
                ('timestamp', models.DateTimeField(blank=True, null=True, verbose_name='Time Stamp in UTC')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polling_status', to='store_time_zone.store')),
            ],
            options={
                'db_table': 'store_status',
            },
        ),
    ]
